name: 🐞 버그
description: 버그를 발견하셨나요? 무언가 제대로 작동하지 않나요? 이 이슈 템플릿을 써주세요!
title: "[Bug]: "
labels: ["🐞 Bug"]
body:
  - type: markdown
    attributes:
      value: |
        이 버그 리포트를 작성해주셔서 감사합니다!
  - type: textarea
    attributes:
      label: 📝 버그 설명
      description: 버그를 설명하고, 무엇이 발생했으며, 어떻게 되어야 할 것으로 기대했는지 알려주세요.
      placeholder: 무슨 일이 발생했는지 알려주세요!
      value: |
        **버그 설명**

        **실제 행동**

        **기대 행동**
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🪜 버그 재현 방법
      description: 가능하다면 이 버그를 재현하는 단계를 여기에 포함시켜주세요!
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. 오류 발생...
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📱 디바이스 환경
      description: |
        예시:
          - **디바이스**: iPhone 14 Pro
          - **iOS**: v16.4
          - **앱 버전**: v1.0.2
      value: |
        - 디바이스:
        - iOS:
        - 앱 버전:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: 💬 추가 정보
      description: |
        링크나 참조자료가 있나요? 이 문제에 대해 더 많은 맥락을 제공할 수 있는 어떤 것이든 알려주세요!

        팁: 이 영역을 클릭하여 하이라이트 한 다음 파일을 드래그하여 이미지나 로그 파일을 첨부할 수 있습니다.
    validations:
      required: false

